#!/bin/sh
# flv_fix_all:
# repair input files (see flv_fix)

for f in "$@" ; do 
  echo $f 
  rm _fixed.flv > /dev/null 2>&1
  flv_fix "$f" _fixed.flv | grep -v "Found TAG"
  mv _fixed.flv "$f"
done

